plugins {
    `java-library`
    id("ekbatan.publishing")
    id("com.github.davidmc24.gradle.plugin.avro") version "1.9.1"
}

ekbatanPublishing {
    artifactId.set("ekbatan-action-event-avro")
    description.set("Avro wire-format ActionEvent (Kafka consumer-side deserialization for Ekbatan outbox).")
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(25))
    }
}

repositories {
    mavenCentral()
}

dependencies {
    api("org.apache.avro:avro:${project.property("avroVersion")}")
}

// The only Java source in this module is generated by the Avro plugin (build/generated-main-avro-java/).
// Suppress the doclint "missing comment" check so we don't warn on hundreds of generated members —
// the generated code still appears in javadoc, keeping the javadoc jar non-empty for Maven Central.
tasks.named<Javadoc>("javadoc") {
    (options as StandardJavadocDocletOptions).addStringOption("Xdoclint:-missing", "-quiet")
}

// Expose the .avsc file as a named output so consumers (e.g. the SMT integration test) can
// resolve its absolute path to mount into containers, instead of hardcoding a relative path.
val actionEventSchema: Configuration by configurations.creating {
    isCanBeConsumed = true
    isCanBeResolved = false
}

artifacts {
    add(actionEventSchema.name, layout.projectDirectory.file("src/main/avro/ActionEvent.avsc"))
}
