import com.google.protobuf.gradle.id

plugins {
    `java-library`
    id("ekbatan.publishing")
    id("com.google.protobuf") version "0.9.4"
}

ekbatanPublishing {
    artifactId.set("ekbatan-action-event-protobuf")
    description.set("Protobuf wire-format ActionEvent (Kafka consumer-side deserialization for Ekbatan outbox).")
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(25))
    }
}

repositories {
    mavenCentral()
}

dependencies {
    api("com.google.protobuf:protobuf-java:${project.property("protobufVersion")}")
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:${project.property("protobufVersion")}"
    }
    generateProtoTasks {
        all().configureEach {
            // Also emit a FileDescriptorSet (.desc) we can expose for runtime use.
            generateDescriptorSet = true
            descriptorSetOptions.includeImports = true
        }
    }
}

// The only Java source in this module is generated by protoc (build/generated/source/proto/main/).
// Suppress the doclint "missing comment" check so we don't warn on hundreds of generated members —
// the generated code still appears in javadoc, keeping the javadoc jar non-empty for Maven Central.
tasks.named<Javadoc>("javadoc") {
    (options as StandardJavadocDocletOptions).addStringOption("Xdoclint:-missing", "-quiet")
}

// Expose the generated descriptor file so consumers (SMT, integration tests) can mount it.
val actionEventDescriptor: Configuration by configurations.creating {
    isCanBeConsumed = true
    isCanBeResolved = false
}

val descriptorFile =
    layout.buildDirectory.file("generated/source/proto/main/descriptor_set.desc")

artifacts {
    add(actionEventDescriptor.name, descriptorFile) {
        builtBy(tasks.named("generateProto"))
    }
}
