rootProject.name = "ekbatan"

include(
    "ekbatan-core",
    "ekbatan-event-streaming",
    "ekbatan-event-streaming:action-event:json",
    "ekbatan-event-streaming:action-event:avro",
    "ekbatan-event-streaming:action-event:protobuf",
    "ekbatan-event-streaming:debezium-smt:protobuf",
    "ekbatan-event-streaming:debezium-smt",
    "ekbatan-event-streaming:debezium-smt:avro",
    "ekbatan-integration-tests:core-repo:shared",
    "ekbatan-integration-tests:core-repo:mariadb:repository",
    "ekbatan-integration-tests:core-repo:mariadb:events",
    "ekbatan-integration-tests:core-repo:mysql:repository",
    "ekbatan-integration-tests:core-repo:mysql:events",
    "ekbatan-integration-tests:core-repo:pg:repository",
    "ekbatan-integration-tests:core-repo:pg:events",
    "ekbatan-integration-tests:postgres-simple",
    "ekbatan-integration-tests:postgres-sharded",
    "ekbatan-integration-tests:event-pipeline",
    "ekbatan-integration-tests:event-pipeline:common",
    "ekbatan-integration-tests:event-pipeline:debezium-kafka-json",
    "ekbatan-integration-tests:event-pipeline:debezium-kafka-avro-smt",
    "ekbatan-integration-tests:event-pipeline:debezium-kafka-protobuf-smt",
    "ekbatan-annotation-processor",
)
