micronaut:
  application:
    name: micronaut-wallet-rest-gradle-native-mariadb

ekbatan:
  namespace: example.wallet.gradle-native-mariadb-micronaut
  sharding:
    defaultShard:
      group: 0
      member: 0
    groups:
      - group: 0
        name: default
        members:
          - member: 0
            name: default
            configs:
              primaryConfig:
                jdbcUrl: jdbc:mariadb://localhost:3306/wallet
                username: wallet
                password: wallet
                driverClassName: org.mariadb.jdbc.Driver
                maximumPoolSize: 20
              jobsConfig:
                jdbcUrl: jdbc:mariadb://localhost:3306/wallet
                username: wallet
                password: wallet
                driverClassName: org.mariadb.jdbc.Driver
                maximumPoolSize: 5
  local-event-handler:
    handling:
      enabled: true